language: node_js

node_js: --lts

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - git config --global user.name 'JounQin'
  - git config --global user.email 'admin@1stg.me'

script:
  - set -e
  - yarn lint
  - yarn build
  - yarn test

before_deploy:
  - set -e
  - npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
  - git remote set-url origin https://user:$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git
  - git fetch origin $TRAVIS_BRANCH:$TRAVIS_BRANCH
  - git checkout $TRAVIS_BRANCH
  - git fetch origin v$(jq -r '.version' package.json) || yarn run standard-version -a --no-verify

deploy:
  provider: script
  skip_cleanup: true
  script: yarn deploy:pre && yarn deploy:run && yarn deploy:post || echo "nothing changed to deploy"
  on:
    branch: master
